export interface Challenge {
    id: number;
    title: string;
    description: string;
    difficulty: 'easy' | 'medium' | 'hard';
    category: string;
    time: string;
    xp: number;
}

export const challenges: Challenge[] = [
    // Wellness Challenges
    {
        id: 1,
        title: 'Morning Sun Exposure',
        description: 'Step outside and spend 5 minutes in natural sunlight to regulate your circadian rhythm.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '5 min',
        xp: 35,
    },
    {
        id: 2,
        title: 'Cold Shower Challenge',
        description: 'End your shower with 30 seconds of cold water to boost alertness and circulation.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '30 sec',
        xp: 70,
    },
    {
        id: 3,
        title: 'Power Nap',
        description: 'Take a 15-minute power nap to recharge your energy and improve cognitive function.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '15 min',
        xp: 60,
    },
    {
        id: 4,
        title: 'Herbal Tea Meditation',
        description: 'Brew herbal tea and spend 10 minutes mindfully drinking it, focusing on aroma and flavors.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '10 min',
        xp: 45,
    },
    {
        id: 5,
        title: 'Digital Sunset',
        description: 'Put away all screens 1 hour before bedtime and engage in analog activities.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '1 hour',
        xp: 100,
    },
    {
        id: 6,
        title: 'Breathing Box Technique',
        description: 'Practice 4-4-4-4 breathing pattern for stress reduction and mental clarity.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '5 min',
        xp: 35,
    },
    {
        id: 7,
        title: 'Mindful Eating',
        description: 'Eat one meal without distractions, focusing on taste and texture.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '30 min',
        xp: 85,
    },
    {
        id: 8,
        title: 'Gratitude Journaling',
        description: 'Write down 3 specific things you\'re grateful for today with details.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '5 min',
        xp: 40,
    },
    {
        id: 9,
        title: 'Progressive Muscle Relaxation',
        description: 'Tense and relax each muscle group for complete physical relaxation.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '15 min',
        xp: 75,
    },
    {
        id: 10,
        title: 'Hydration Challenge',
        description: 'Drink a glass of water every hour and track your intake.',
        difficulty: 'easy',
        category: 'Wellness',
        time: 'all day',
        xp: 90,
    },

    // Fitness Challenges
    {
        id: 11,
        title: 'Plank Challenge',
        description: 'Hold a plank position for as long as possible, beat your record by 10 seconds.',
        difficulty: 'medium',
        category: 'Fitness',
        time: '3 min',
        xp: 80,
    },
    {
        id: 12,
        title: 'Bodyweight Squats',
        description: 'Perform 20 squats with proper form to strengthen your lower body.',
        difficulty: 'medium',
        category: 'Fitness',
        time: '5 min',
        xp: 90,
    },
    {
        id: 13,
        title: 'Desk Stretches',
        description: 'Perform 5 different stretches at your desk to combat prolonged sitting.',
        difficulty: 'easy',
        category: 'Fitness',
        time: '5 min',
        xp: 35,
    },
    {
        id: 14,
        title: 'Push-up Pyramid',
        description: 'Do push-ups in sequence: 1, 2, 3, 4, 5, then back down 4, 3, 2, 1.',
        difficulty: 'hard',
        category: 'Fitness',
        time: '10 min',
        xp: 120,
    },
    {
        id: 15,
        title: 'Balance Challenge',
        description: 'Stand on one foot for 30 seconds, switch feet, repeat 3 times each.',
        difficulty: 'easy',
        category: 'Fitness',
        time: '5 min',
        xp: 35,
    },
    {
        id: 16,
        title: 'High Knees Sprint',
        description: 'Perform high knees for 30 seconds, rest 30 seconds, repeat 3 times.',
        difficulty: 'medium',
        category: 'Fitness',
        time: '5 min',
        xp: 70,
    },
    {
        id: 17,
        title: 'Wall Sits',
        description: 'Perform wall sit exercise for 45 seconds to build lower body endurance.',
        difficulty: 'medium',
        category: 'Fitness',
        time: '3 min',
        xp: 65,
    },
    {
        id: 18,
        title: 'Burpee Challenge',
        description: 'Perform 10 burpees with proper form, focus on control not speed.',
        difficulty: 'hard',
        category: 'Fitness',
        time: '8 min',
        xp: 110,
    },
    {
        id: 19,
        title: 'Flexibility Flow',
        description: 'Complete 10-minute stretching routine focusing on major muscle groups.',
        difficulty: 'easy',
        category: 'Fitness',
        time: '10 min',
        xp: 55,
    },
    {
        id: 20,
        title: 'Stair Climbing',
        description: 'Find stairs and climb up and down 3 times at brisk pace.',
        difficulty: 'medium',
        category: 'Fitness',
        time: '10 min',
        xp: 80,
    },

    // Education Challenges
    {
        id: 21,
        title: 'Learn 5 New Words',
        description: 'Discover 5 new words in foreign language or advanced vocabulary.',
        difficulty: 'easy',
        category: 'Education',
        time: '10 min',
        xp: 60,
    },
    {
        id: 22,
        title: 'Wikipedia Deep Dive',
        description: 'Start with random Wikipedia article, follow links for 15 minutes of learning.',
        difficulty: 'easy',
        category: 'Education',
        time: '15 min',
        xp: 70,
    },
    {
        id: 23,
        title: 'Documentary Episode',
        description: 'Watch 20-minute educational documentary on unfamiliar subject.',
        difficulty: 'medium',
        category: 'Education',
        time: '25 min',
        xp: 95,
    },
    {
        id: 24,
        title: 'Speed Math Practice',
        description: 'Practice mental math with 20 arithmetic problems without calculator.',
        difficulty: 'medium',
        category: 'Education',
        time: '10 min',
        xp: 80,
    },
    {
        id: 25,
        title: 'Memory Palace',
        description: 'Create memory palace to memorize 10 items using spatial visualization.',
        difficulty: 'hard',
        category: 'Education',
        time: '15 min',
        xp: 120,
    },
    {
        id: 26,
        title: 'TED Talk',
        description: 'Watch inspiring TED talk under 15 minutes on topic outside your interests.',
        difficulty: 'easy',
        category: 'Education',
        time: '15 min',
        xp: 70,
    },
    {
        id: 27,
        title: 'Language Practice',
        description: 'Practice foreign language for 10 minutes using apps or flashcards.',
        difficulty: 'medium',
        category: 'Education',
        time: '10 min',
        xp: 80,
    },
    {
        id: 28,
        title: 'Brain Teaser',
        description: 'Solve 3 different brain teasers or logic puzzles.',
        difficulty: 'medium',
        category: 'Education',
        time: '12 min',
        xp: 85,
    },
    {
        id: 29,
        title: 'Historical Research',
        description: 'Research one historical event that happened on today\'s date.',
        difficulty: 'easy',
        category: 'Education',
        time: '15 min',
        xp: 75,
    },
    {
        id: 30,
        title: 'Science Experiment',
        description: 'Conduct simple science experiment using household items.',
        difficulty: 'medium',
        category: 'Education',
        time: '20 min',
        xp: 100,
    },

    // Productivity Challenges
    {
        id: 31,
        title: 'Email Zero',
        description: 'Process all emails - delete, archive, respond, or schedule for later.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '20 min',
        xp: 90,
    },
    {
        id: 32,
        title: 'Desktop Cleanup',
        description: 'Organize digital desktop by creating folders and removing unnecessary files.',
        difficulty: 'easy',
        category: 'Productivity',
        time: '10 min',
        xp: 50,
    },
    {
        id: 33,
        title: 'Task Prioritization',
        description: 'List pending tasks and rank using Eisenhower Matrix (urgent/important).',
        difficulty: 'easy',
        category: 'Productivity',
        time: '15 min',
        xp: 70,
    },
    {
        id: 34,
        title: 'Pomodoro Session',
        description: 'Complete 25-minute focused work session followed by 5-minute break.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '30 min',
        xp: 100,
    },
    {
        id: 35,
        title: 'Calendar Review',
        description: 'Review and optimize calendar for next week, block time for important tasks.',
        difficulty: 'easy',
        category: 'Productivity',
        time: '10 min',
        xp: 60,
    },
    {
        id: 36,
        title: 'Digital Declutter',
        description: 'Unsubscribe from 5 email lists or unfollow 10 social media accounts.',
        difficulty: 'easy',
        category: 'Productivity',
        time: '10 min',
        xp: 55,
    },
    {
        id: 37,
        title: 'Goal Setting',
        description: 'Write 3 specific, measurable goals for this month with action steps.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '20 min',
        xp: 85,
    },
    {
        id: 38,
        title: 'Morning Routine Optimization',
        description: 'Design more efficient morning routine that saves 10 minutes.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '20 min',
        xp: 80,
    },
    {
        id: 39,
        title: 'Single-Tasking',
        description: 'Work on one important task with complete focus for 45 minutes.',
        difficulty: 'hard',
        category: 'Productivity',
        time: '45 min',
        xp: 115,
    },
    {
        id: 40,
        title: 'Weekly Review',
        description: 'Review accomplishments, challenges, and plans for next week.',
        difficulty: 'easy',
        category: 'Productivity',
        time: '15 min',
        xp: 65,
    },

    // Creative Challenges
    {
        id: 41,
        title: 'Free Writing',
        description: 'Write continuously for 10 minutes without stopping or editing.',
        difficulty: 'easy',
        category: 'Creative',
        time: '10 min',
        xp: 55,
    },
    {
        id: 42,
        title: 'Photo Challenge',
        description: 'Take 10 photos focusing on interesting angles and lighting.',
        difficulty: 'easy',
        category: 'Creative',
        time: '15 min',
        xp: 60,
    },
    {
        id: 43,
        title: 'Doodle Session',
        description: 'Spend 15 minutes sketching without worrying about perfection.',
        difficulty: 'easy',
        category: 'Creative',
        time: '15 min',
        xp: 50,
    },
    {
        id: 44,
        title: 'Music Creation',
        description: 'Create simple beat or melody using voice memos or available instruments.',
        difficulty: 'medium',
        category: 'Creative',
        time: '20 min',
        xp: 90,
    },
    {
        id: 45,
        title: 'Poetry Writing',
        description: 'Write short poem about your mood, weather, or daily observation.',
        difficulty: 'medium',
        category: 'Creative',
        time: '12 min',
        xp: 70,
    },
    {
        id: 46,
        title: 'Origami Challenge',
        description: 'Learn new origami design using online tutorials.',
        difficulty: 'medium',
        category: 'Creative',
        time: '15 min',
        xp: 75,
    },
    {
        id: 47,
        title: 'Color Palette Study',
        description: 'Choose photo or scene and identify all colors, create your palette.',
        difficulty: 'easy',
        category: 'Creative',
        time: '10 min',
        xp: 45,
    },
    {
        id: 48,
        title: 'Storytelling Practice',
        description: 'Write 5-minute story about interesting person you encountered.',
        difficulty: 'medium',
        category: 'Creative',
        time: '10 min',
        xp: 65,
    },

    // Social Challenges
    {
        id: 49,
        title: 'Reconnection Call',
        description: 'Call old friend you haven\'t spoken to in while to catch up.',
        difficulty: 'medium',
        category: 'Social',
        time: '15 min',
        xp: 80,
    },
    {
        id: 50,
        title: 'Random Act of Kindness',
        description: 'Perform unexpected kind act - hold door, pay for coffee, offer help.',
        difficulty: 'easy',
        category: 'Social',
        time: '10 min',
        xp: 70,
    },
    {
        id: 51,
        title: 'Active Listening',
        description: 'Have conversation focusing entirely on listening and asking questions.',
        difficulty: 'medium',
        category: 'Social',
        time: '20 min',
        xp: 85,
    },
    {
        id: 52,
        title: 'Thank You Note',
        description: 'Write heartfelt thank you note to someone who impacted your life.',
        difficulty: 'easy',
        category: 'Social',
        time: '10 min',
        xp: 60,
    },
    {
        id: 53,
        title: 'Family Connection',
        description: 'Reach out to family member for meaningful conversation.',
        difficulty: 'medium',
        category: 'Social',
        time: '20 min',
        xp: 90,
    },
    {
        id: 54,
        title: 'Empathy Practice',
        description: 'See situation from three different perspectives to build understanding.',
        difficulty: 'medium',
        category: 'Social',
        time: '15 min',
        xp: 75,
    },

    // Cooking Challenges
    {
        id: 55,
        title: 'New Recipe Trial',
        description: 'Try cooking recipe from cuisine you\'ve never attempted before.',
        difficulty: 'medium',
        category: 'Cooking',
        time: '45 min',
        xp: 100,
    },
    {
        id: 56,
        title: 'Spice Experiment',
        description: 'Cook familiar dish with new spice combination you\'ve never tried.',
        difficulty: 'easy',
        category: 'Cooking',
        time: '30 min',
        xp: 65,
    },
    {
        id: 57,
        title: 'Zero Waste Cooking',
        description: 'Prepare meal using ingredients you have, minimize food waste.',
        difficulty: 'medium',
        category: 'Cooking',
        time: '30 min',
        xp: 80,
    },
    {
        id: 58,
        title: 'Knife Skills Practice',
        description: 'Practice proper knife techniques chopping vegetables safely.',
        difficulty: 'medium',
        category: 'Cooking',
        time: '15 min',
        xp: 70,
    },
    {
        id: 59,
        title: 'Healthy Substitution',
        description: 'Take favorite recipe and make it healthier by substituting ingredients.',
        difficulty: 'medium',
        category: 'Cooking',
        time: '35 min',
        xp: 85,
    },
    {
        id: 60,
        title: 'Mindful Cooking',
        description: 'Prepare simple meal practicing mindfulness - focus on textures and aromas.',
        difficulty: 'easy',
        category: 'Cooking',
        time: '25 min',
        xp: 75,
    },

    // Additional Challenges (61-100)
    {
        id: 61,
        title: 'Phone-Free Hour',
        description: 'Spend one hour without your phone - read, draw, or have face-to-face conversations.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '1 hour',
        xp: 95,
    },
    {
        id: 62,
        title: 'Learn a Magic Trick',
        description: 'Watch tutorial and practice simple magic trick you can show to others.',
        difficulty: 'medium',
        category: 'Creative',
        time: '20 min',
        xp: 80,
    },
    {
        id: 63,
        title: 'Nature Photography',
        description: 'Take 20 photos of nature focusing on details like leaves, textures, or patterns.',
        difficulty: 'easy',
        category: 'Creative',
        time: '25 min',
        xp: 65,
    },
    {
        id: 64,
        title: 'Voice Message Marathon',
        description: 'Send voice messages instead of texts for all communications today.',
        difficulty: 'easy',
        category: 'Social',
        time: 'all day',
        xp: 85,
    },
    {
        id: 65,
        title: 'Speed Cleaning',
        description: 'Set 15-minute timer and clean as much as possible in one room.',
        difficulty: 'easy',
        category: 'Productivity',
        time: '15 min',
        xp: 70,
    },
    {
        id: 66,
        title: 'Lemon Water Detox',
        description: 'Start day with warm lemon water and drink it before every meal.',
        difficulty: 'easy',
        category: 'Wellness',
        time: 'all day',
        xp: 60,
    },
    {
        id: 67,
        title: 'Memory Game',
        description: 'Memorize and recite 20-item shopping list or poem without looking.',
        difficulty: 'hard',
        category: 'Education',
        time: '20 min',
        xp: 110,
    },
    {
        id: 68,
        title: 'Compliment Journal',
        description: 'Write down every compliment you receive and give today.',
        difficulty: 'easy',
        category: 'Social',
        time: '10 min',
        xp: 45,
    },
    {
        id: 69,
        title: 'Dance Break',
        description: 'Put on favorite song and dance freely for 5 minutes.',
        difficulty: 'easy',
        category: 'Fitness',
        time: '5 min',
        xp: 40,
    },
    {
        id: 70,
        title: 'Local History Research',
        description: 'Research interesting historical fact about your neighborhood or city.',
        difficulty: 'medium',
        category: 'Education',
        time: '15 min',
        xp: 75,
    },
    {
        id: 71,
        title: 'Herb Garden Start',
        description: 'Plant herbs in small pots or start sprouting seeds for future garden.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '30 min',
        xp: 90,
    },
    {
        id: 72,
        title: 'Podcast Speed Learning',
        description: 'Listen to educational podcast at 1.5x speed to practice focused attention.',
        difficulty: 'medium',
        category: 'Education',
        time: '20 min',
        xp: 85,
    },
    {
        id: 73,
        title: 'Handwriting Practice',
        description: 'Write one page by hand to improve handwriting and motor skills.',
        difficulty: 'easy',
        category: 'Creative',
        time: '15 min',
        xp: 55,
    },
    {
        id: 74,
        title: 'Sunrise or Sunset',
        description: 'Watch complete sunrise or sunset without distractions.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '20 min',
        xp: 70,
    },
    {
        id: 75,
        title: 'Quick Sketch',
        description: 'Draw your immediate surroundings in 10 minutes using any materials.',
        difficulty: 'easy',
        category: 'Creative',
        time: '10 min',
        xp: 50,
    },
    {
        id: 76,
        title: 'Social Media Audit',
        description: 'Review and unfollow accounts that don\'t bring joy or value.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '20 min',
        xp: 80,
    },
    {
        id: 77,
        title: 'Breathing Exercises',
        description: 'Try 3 different breathing techniques: box breathing, 4-7-8, and bellows.',
        difficulty: 'medium',
        category: 'Wellness',
        time: '15 min',
        xp: 75,
    },
    {
        id: 78,
        title: 'Random Wikipedia',
        description: 'Click random article button 10 times and learn something from each.',
        difficulty: 'easy',
        category: 'Education',
        time: '20 min',
        xp: 70,
    },
    {
        id: 79,
        title: 'Stranger Smile',
        description: 'Make eye contact and smile at 5 strangers throughout the day.',
        difficulty: 'medium',
        category: 'Social',
        time: 'all day',
        xp: 90,
    },
    {
        id: 80,
        title: 'Food Meditation',
        description: 'Eat one snack extremely slowly, focusing on every bite and flavor.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '10 min',
        xp: 50,
    },
    {
        id: 81,
        title: 'Old Photos Review',
        description: 'Look through old photos and remember positive memories for 15 minutes.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '15 min',
        xp: 60,
    },
    {
        id: 82,
        title: 'Micro Workout',
        description: 'Do 10 squats, 10 push-ups, 30-second plank every hour for 4 hours.',
        difficulty: 'hard',
        category: 'Fitness',
        time: '4 hours',
        xp: 120,
    },
    {
        id: 83,
        title: 'Letter Writing',
        description: 'Write physical letter to someone you care about and mail it.',
        difficulty: 'medium',
        category: 'Social',
        time: '30 min',
        xp: 95,
    },
    {
        id: 84,
        title: 'Trivia Challenge',
        description: 'Test yourself with 20 trivia questions from different categories.',
        difficulty: 'medium',
        category: 'Education',
        time: '15 min',
        xp: 80,
    },
    {
        id: 85,
        title: 'Posture Practice',
        description: 'Set hourly reminders to check and improve posture throughout day.',
        difficulty: 'easy',
        category: 'Wellness',
        time: 'all day',
        xp: 85,
    },
    {
        id: 86,
        title: 'Meal Planning',
        description: 'Plan all meals for next 3 days including shopping list.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '25 min',
        xp: 90,
    },
    {
        id: 87,
        title: 'Joke Learning',
        description: 'Learn 3 clean jokes and practice telling them with good timing.',
        difficulty: 'easy',
        category: 'Social',
        time: '15 min',
        xp: 65,
    },
    {
        id: 88,
        title: 'Closet Organization',
        description: 'Organize one section of closet and donate items you don\'t wear.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '30 min',
        xp: 85,
    },
    {
        id: 89,
        title: 'Balance Training',
        description: 'Practice balancing on one foot while brushing teeth and doing daily tasks.',
        difficulty: 'easy',
        category: 'Fitness',
        time: '10 min',
        xp: 45,
    },
    {
        id: 90,
        title: 'Weather Observation',
        description: 'Spend 10 minutes observing and documenting current weather patterns.',
        difficulty: 'easy',
        category: 'Education',
        time: '10 min',
        xp: 40,
    },
    {
        id: 91,
        title: 'Gratitude Call',
        description: 'Call someone to specifically thank them for something they did.',
        difficulty: 'medium',
        category: 'Social',
        time: '15 min',
        xp: 85,
    },
    {
        id: 92,
        title: 'Ingredient Challenge',
        description: 'Create meal using only 5 ingredients you currently have at home.',
        difficulty: 'medium',
        category: 'Cooking',
        time: '30 min',
        xp: 80,
    },
    {
        id: 93,
        title: 'Power Posing',
        description: 'Practice confident body language and power poses for 5 minutes.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '5 min',
        xp: 35,
    },
    {
        id: 94,
        title: 'Word Association',
        description: 'Play word association game with yourself or others for mental agility.',
        difficulty: 'easy',
        category: 'Education',
        time: '10 min',
        xp: 50,
    },
    {
        id: 95,
        title: 'Shoe Organization',
        description: 'Clean and organize all shoes, donate pairs you never wear.',
        difficulty: 'easy',
        category: 'Productivity',
        time: '20 min',
        xp: 70,
    },
    {
        id: 96,
        title: 'Eye Contact Practice',
        description: 'Practice maintaining comfortable eye contact in all conversations today.',
        difficulty: 'medium',
        category: 'Social',
        time: 'all day',
        xp: 95,
    },
    {
        id: 97,
        title: 'Texture Exploration',
        description: 'Touch and mindfully experience 10 different textures around you.',
        difficulty: 'easy',
        category: 'Wellness',
        time: '10 min',
        xp: 45,
    },
    {
        id: 98,
        title: 'News Summary',
        description: 'Read news and write 3-sentence summary of most important story.',
        difficulty: 'medium',
        category: 'Education',
        time: '15 min',
        xp: 75,
    },
    {
        id: 99,
        title: 'Walking Meeting',
        description: 'Take phone call or meeting while walking instead of sitting.',
        difficulty: 'easy',
        category: 'Fitness',
        time: '20 min',
        xp: 65,
    },
    {
        id: 100,
        title: 'Digital Photo Cleanup',
        description: 'Delete 50 unnecessary photos from phone and organize remaining ones.',
        difficulty: 'medium',
        category: 'Productivity',
        time: '25 min',
        xp: 80,
    }
];

export const getRandomChallenge = (): Challenge => {
    const randomIndex = Math.floor(Math.random() * challenges.length);
    return challenges[randomIndex];
};

export const getChallengesByDifficulty = (difficulty: 'easy' | 'medium' | 'hard'): Challenge[] => {
    return challenges.filter(challenge => challenge.difficulty === difficulty);
};

export const getChallengesByCategory = (category: string): Challenge[] => {
    return challenges.filter(challenge => challenge.category === category);
};

export const getChallengesByTimeCommitment = (maxMinutes: number): Challenge[] => {
    return challenges.filter(challenge => {
        const timeStr = challenge.time.toLowerCase();
        if (timeStr.includes('all day')) return false;
        const minutes = parseInt(timeStr);
        return !isNaN(minutes) && minutes <= maxMinutes;
    });
};

export const getRandomChallengeByCategory = (category: string): Challenge | null => {
    const categoryChanges = getChallengesByCategory(category);
    if (categoryChanges.length === 0) return null;
    const randomIndex = Math.floor(Math.random() * categoryChanges.length);
    return categoryChanges[randomIndex];
};

export const getChallengeStats = () => {
    const stats = {
        total: challenges.length,
        byDifficulty: { easy: 0, medium: 0, hard: 0 },
        byCategory: {} as { [key: string]: number },
        totalXP: challenges.reduce((sum, challenge) => sum + challenge.xp, 0)
    };
    
    challenges.forEach(challenge => {
        stats.byDifficulty[challenge.difficulty]++;
        stats.byCategory[challenge.category] = (stats.byCategory[challenge.category] || 0) + 1;
    });
    
    return stats;
};